name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.4
      with:
        ssh-private-key: ${{ secrets.EC2_SSH_KEY }} # Usa el nombre que le diste al secreto

    - name: Create directory on EC2 instance
      run: |
        ssh -o StrictHostKeyChecking=no -i ${{ secrets.EC2_SSH_KEY }} ubuntu@ec2-18-206-88-149.compute-1.amazonaws.com << 'EOF'
          mkdir -p ~/pruebaFront
          exit
        EOF

    - name: Copy test.txt to EC2 instance
      run: |
        scp -o StrictHostKeyChecking=no -i ${{ secrets.EC2_SSH_KEY }} ./test.txt ubuntu@ec2-18-206-88-149.compute-1.amazonaws.com:~/pruebaFront/test.txt
