name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Create directory on EC2 instance
      run: |
        echo "${{ secrets.EC2_SSH_KEY }}" > /tmp/vockey.pem
        chmod 600 /tmp/vockey.pem
        ssh -o StrictHostKeyChecking=no -i /tmp/vockey.pem ubuntu@ec2-18-206-88-149.compute-1.amazonaws.com << 'EOF'
          mkdir -p ~/pruebaFront
          exit
        EOF

    - name: Copy test.txt to EC2 instance
      run: |
        scp -o StrictHostKeyChecking=no -i /tmp/vockey.pem ./test.txt ubuntu@ec2-18-206-88-149.compute-1.amazonaws.com:~/pruebaFront/test.txt
