name: Build and Deploy Angular to EC2

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'

    - name: Install Angular dependencies
      run: |
        npm install -g @angular/cli
        npm install

    - name: Build Angular project
      run: |
        ng build --configuration production

    - name: List files in dist
      run: ls -R ./dist

    - name: Set up SSH and copy build to EC2
      run: |
        echo "${{ secrets.EC2_SSH_KEY }}" > /tmp/vockey.pem
        chmod 600 /tmp/vockey.pem

        # Copiar archivos compilados a la instancia EC2 con sudo
        scp -o StrictHostKeyChecking=no -i /tmp/vockey.pem -r ./dist/front/* ubuntu@${{ secrets.EC2_DNS }}:/tmp/
        ssh -o StrictHostKeyChecking=no -i /tmp/vockey.pem ubuntu@${{ secrets.EC2_DNS }} "sudo cp -r /tmp/* /var/www/html/"
